[package]
name = "img-to-pdf"
version = "0.1.0"
edition = "2018"

[features]
default = []
printpdf_ = ["printpdf"]
genpdf_ = ["genpdf"]

[dependencies]
anyhow = "1"
printpdf = { version = "0.4", optional = true }
genpdf = { version = "0.2", optional = true, features = ["images"] }

