[package]
name = "img-to-pdf"
version = "0.1.0"
edition = "2018"

[features]
default = []
pdfcreate_ = ["pdf-create"]
printpdf_ = ["printpdf"]
genpdf_ = ["genpdf"]

[dependencies]
anyhow = "1"
pdf-create = { version = "0.1", optional = true }
printpdf = { version = "0.4", optional = true }
genpdf = { version = "0.2", optional = true, features = ["images"] }

